site.host=https://lanwen.github.io/frmtr
render.index=false
render.archive=false
render.feed=false
render.tags=false
render.sitemap=false
template.landing.file=index.ftl
template.encoding=UTF-8
output.extension=.html
default.status=published
