FROM ghcr.io/graalvm/native-image-community:25 AS build

WORKDIR /workspace

COPY gradle ./gradle
COPY gradlew settings.gradle.kts build.gradle.kts ./
COPY frmtr-core ./frmtr-core
COPY frmtr-tooling ./frmtr-tooling
COPY frmtr-cli ./frmtr-cli
COPY frmtr-native-image-support ./frmtr-native-image-support

RUN ./gradlew --no-daemon :frmtr-cli:nativeCompile

FROM scratch AS artifact
COPY --from=build /workspace/frmtr-cli/build/native/nativeCompile/frmtr /frmtr
