[versions]
assertj = "3.27.7"
javaparser = "3.28.2"
jgit = "7.6.0.202603022253-r"
junit-jupiter = "6.0.3"
graalvm-native-buildtools = "0.11.5"
gradle-plugin-publish = "2.1.1"
graalvm-nativeimage = "25.0.3"
jbake = "2.7.0"
jmh = "1.37"
jreleaser = "1.24.0"
picocli = "4.7.7"
slf4j = "2.0.17"

[libraries]
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
javaparser-core = { module = "com.github.javaparser:javaparser-core", version.ref = "javaparser" }
graalvm-nativeimage = { module = "org.graalvm.sdk:nativeimage", version.ref = "graalvm-nativeimage" }
jbake-core = { module = "org.jbake:jbake-core", version.ref = "jbake" }
jgit = { module = "org.eclipse.jgit:org.eclipse.jgit", version.ref = "jgit" }
jmh-core = { module = "org.openjdk.jmh:jmh-core", version.ref = "jmh" }
jmh-generator-annprocess = { module = "org.openjdk.jmh:jmh-generator-annprocess", version.ref = "jmh" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
picocli = { module = "info.picocli:picocli", version.ref = "picocli" }
picocli-codegen = { module = "info.picocli:picocli-codegen", version.ref = "picocli" }
slf4j-nop = { module = "org.slf4j:slf4j-nop", version.ref = "slf4j" }

[plugins]
graalvm-native = { id = "org.graalvm.buildtools.native", version.ref = "graalvm-native-buildtools" }
gradle-plugin-publish = { id = "com.gradle.plugin-publish", version.ref = "gradle-plugin-publish" }
jreleaser = { id = "org.jreleaser", version.ref = "jreleaser" }
