package dev.lanwen.frmtr;

import static org.assertj.core.api.Assertions.assertThat;

import com.github.javaparser.JavaParser;
import com.github.javaparser.JavaToken;
import com.github.javaparser.ParseResult;
import com.github.javaparser.ParseStart;
import com.github.javaparser.ParserConfiguration;
import com.github.javaparser.Providers;
import com.github.javaparser.TokenRange;
import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.comments.Comment;
import java.util.ArrayList;
import java.util.Collections;
import java.util.IdentityHashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;
import java.util.stream.Stream;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

/**
 * Output-level comment-presence net — the CI gate for "the formatter never drops a comment" (roadmap S7 part 2;
 * promoted from the {@code inv/comment-presence} diagnostic).
 *
 * <p><strong>Why this is the gate and {@code assertAllCommentsAccounted} is not.</strong> The accounting guardrail
 * flags a comment when it was not <em>registered</em> in the formatter's claimed / raw-accounted sets. That
 * registration is keyed on JavaParser {@link Comment} object identity, so it is a <em>proxy</em> for "did the comment's
 * text reach the output", not a measurement of it: a comment rendered through a path that never records accounting, or
 * recorded under a different comment identity, is flagged even though its text is present (over-reports), and an
 * AST-invisible orphan it never traverses is missed (under-reports). This net answers the real question directly: it
 * compares the <em>lexer comment-token multiset</em> of the INPUT against that of the {@link Frmtr#format formatted
 * OUTPUT}, and fails when any input comment content appears fewer times in the output than in the input. The lexer
 * count is ground truth — it counts the actual {@code //} and {@code /* *}{@code /} tokens in the source bytes, so it
 * cannot phantom-drop or phantom-gain the way an attributed-comment traversal can.
 *
 * <p><strong>What it asserts, over what corpus.</strong> Two parameterized passes fail on any non-excluded
 * {@code (fixture, shape)} that drops a comment: (1) every golden fixture input at its own variant options, verbatim;
 * (2) collapsed/expanded whitespace perturbations of every golden input at default options, generated by the shared
 * {@link SourceShapePerturbation} engine that {@code IdempotencePropertyTest} also uses (so a comment dropped only when
 * the layout moves is still caught — that shape-dependent ownership is the B1 thesis). Tolerant normalization (see
 * {@link #normalizeRawComment}) makes
 * re-indentation, trailing-whitespace strip, and block {@code *}-prefix re-shaping invisible, so only genuine textual
 * <em>absence</em> fails.
 *
 * <p><strong>The exclusion list ({@link #KNOWN_DROPS}) is the S9 backlog.</strong> It is seeded with exactly the
 * {@code (fixture, shape)} cases that drop a comment on this branch today, each annotated with the dropped text and a
 * pointer to the S9 cluster that owns the fix. This makes the net green now while it bites on any <em>new</em> drop
 * immediately. As each S9 cluster lands a real fix, its entries are removed here in the same change; the net is fully
 * green with an empty exclusion list when S9 completes. The exclusion list is never widened to mask a regression — a
 * new drop outside the backlog must be fixed or diagnosed, not parked (see the class's STOP conditions in
 * {@code docs/proposals/comment-data-loss.md}).
 *
 * <p>{@link #printReport()} still drains a full per-drop inventory to stdout as a development aid; the build outcome is
 * decided by the per-case assertions, not the report.
 */
final class CommentPresenceDiagnosticTest {

    /**
     * The S9 comment-drop backlog: {@code (fixture, shape)} display names whose formatting still drops a comment on this
     * branch, each kept out of the asserting net until its fix lands.
     *
     * <p>Each entry's value records the comment text(s) the fixture loses and the work the fix belongs to, so the parked
     * finding stays honest and reviewable. The remaining entries fall into two buckets, both documented per-entry:
     *
     * <ul>
     *   <li><strong>needs B1</strong> — source-shape consolidation. The comment is dropped only when the whitespace
     *       perturbation moves it off the source line/column its ownership recovery keys on (or JavaParser re-attributes
     *       it across constructs under collapse). These are the headline evidence for the B1 {@code SourceShapePolicy};
     *       a shape-independent fix is the policy consolidation, not a local printer patch.
     *   <li><strong>needs B2</strong> — deterministic, attachment-independent comment ownership. The Guava copyright
     *       file-header has an empty AST attachment ({@code getAllContainedComments} never returns it), so no
     *       attachment-based path can reach it.
     * </ul>
     *
     * <p>The structural drops that did <em>not</em> depend on incidental layout — comments orphaned between top-level
     * types, before a {@code case}, around a single text-block argument, trailing a block's last statement or a call's
     * last argument, and an inline block comment between an annotation and its member — are fixed and removed from this
     * list (see the branch's per-cluster commits).
     *
     * <p><strong>Do not add entries to silence a regression.</strong> This list only ever shrinks. A drop on a case not
     * already here is a new data-loss bug the net is meant to catch.
     */
    private static final Map<String, String> KNOWN_DROPS = knownDrops();

    private static Map<String, String> knownDrops() {
        Map<String, String> drops = new TreeMap<>();

        // -- P1: drops only when whitespace is perturbed; shape-dependent ownership (B1 evidence). --

        // control-condition -- FIXED (source-order ownership; rendering stays line-based). Two sub-mechanisms, both the
        // shape-independent orphan-recovery shape:
        //  1. A control-condition leading line comment (while ( // note value )) re-buckets from the condition's own
        //     contained trivia to the enclosing WhileStmt/SwitchStmt/SwitchExpr ORPHAN pool under collapse/expand.
        //     JavaCommentPlacementPolicy.leadingConditionComments recovers the control-statement orphan line comments that
        //     begin after the statement's keyword and before the condition; ControlConditionPrinter.detachedCondition
        //     LineComments unions them with the condition's contained trivia (deduped by identity, source-ordered) and the
        //     existing line-based broken-condition render gate prints them unchanged. Logical &&/|| conditions are excluded
        //     (their operand-leading comments are an IfStmt orphan even at @default and are rendered operand-by-operand), so
        //     @default stays byte-identical.
        //  2. A close-paren trailing line comment (if (cond) // note { body }) re-buckets onto the enclosing IfStmt/switch
        //     orphan pool when expand pushes it onto its own line below the `)`. ControlConditionPrinter.closeParenTrailing
        //     LineComment falls back to JavaCommentPlacementPolicy.trailingConditionComments (control-statement orphan line
        //     comments after the condition and before the then/body) when the inline raw-slice path finds nothing; the
        //     comment value comes from the orphan itself, not the raw slice. At @default the comment is inline after `)`,
        //     so the raw-slice path renders it and the orphan pool is empty there.

        // if-statement -- FIXED (four sub-mechanisms, all shape-independent comment ownership; rendering stays
        // line/column-based and @default is byte-identical):
        //  1. logical-condition operand-leading line comments ("legacy key envelope ...", the token-envelope-03 URL):
        //     a multi-line &&/|| condition's first operand-leading comment re-buckets to the IfStmt orphan pool, but the
        //     operand-by-operand renderer (BinaryExpressionPrinter.linesWithComments) only read the condition's
        //     own/contained trivia. lineCommentsBeforeFirstOperand now adds a fourth, source-order source:
        //     JavaCommentPlacementPolicy.leadingConditionComments(parent, expression) when the binary expression is the
        //     condition/selector of its enclosing if/while/switch statement or switch expression. At @default that comment
        //     is either already recovered by the line-keyed sources (deduped by identity) or is the expression's own
        //     contained trivia (which the statement does not hold as an orphan), so nothing is added there. This is the
        //     logical-condition counterpart that ControlConditionPrinter.recoveredLeadingConditionComments deliberately
        //     skips because logical conditions render operand-by-operand.
        //  2. else-leading line comment (// test\nelse): re-buckets from the else statement's own trivia to the IfStmt
        //     orphan pool under expand. StatementPrinter.elseLeadingLineComment falls back to gapLineCommentsBefore(then,
        //     else, [if]) when the genuinely-leading own line comment is absent. The own predicate also now requires the
        //     comment to start before the else node, so an else-trailing line comment is no longer mis-claimed as leading
        //     (the fix that drained sub-mechanism 3 at collapse).
        //  3. else-block trailing line comment (} else {} // test) under collapse: the comment lands on the shared else
        //     `}` position so trailingLineComment's startsAfterEndOf(else) own path still selects it -- once the leading
        //     slot (mechanism 2) stops stealing it -- and StatementPrinter.elseTrailingLineComment additionally falls back
        //     to trailingLineCommentsAfter(if, else, empty) for the orphan-bucket shape, mirroring the try-clause handoff.
        //  4. then/else block comment (} /* test */ else) under expand: blockCommentBetweenThenAndElse keeps its original
        //     column arithmetic as the own path (that window is what distinguishes } /* note */ else from else /* note */
        //     {, both of which are the else node's own block comment at @default) and adds an IfStmt-orphan fallback that
        //     recovers the orphan block comment lying source-order between the then end and the else begin. The fallback
        //     sees only orphans, so an else-leading block comment (still the else node's own trivia under perturbation) is
        //     never claimed there and @default stays byte-identical.

        // labeled-statement @ collapsed -- DEFERRED (one residual before-label drop). The leading-comment recovery for a
        // labeled statement now has a third, @collapsed-only path: StatementPrinter.recoveredLabeledLeadingComments adds
        // a GATED fallback over the comments JavaCommentPlacementPolicy.gapCommentsBetween selects source-order between
        // the label and the body across the LabeledStmt orphan pool, the label SimpleName own, and the nested ForEachStmt
        // own/orphan buckets. It dedupes against the raw-slice path two ways: (1) a STRING guard excludes any candidate
        // whose normalized text the raw slice (StatementPrinter.labeledStatementLeadingComments, a List<String> that does
        // not claim through CommentTracker) already produced for this statement, comparing with the same normalization
        // this net uses (normalizeRawComment); and (2) an identity claim via CommentTracker.comment renders an
        // already-claimed comment (the envelope path's LabeledStmt-own leading) empty. At @default the raw slice produces
        // every between-label-and-body leading comment, so the string guard removes all candidates and @default stays
        // byte-identical (verified: git diff main on the golden corpus is empty). That fallback clears "comment1"
        // (22->22) and "comment2" (14->14) fully and 13 of 14 "Label statement".
        //   The single residual drop is a DIFFERENT mechanism the between-label-and-body scope deliberately does not
        // reach: in the all-line method's third statement the leading comment sits BEFORE the label (`// Label statement`
        // then `loop:`), so at @default it is the LabeledStmt's OWN comment (the envelope renders it). Under collapse it
        // re-buckets onto the PREVIOUS sibling's ForEachStmt as that node's own comment (positioned after the prior
        // for-loop's `}`), so it is owned by neither this statement's label/body buckets nor its own/orphan pool. Reaching
        // a preceding sibling's own-comment slot to recover it is exactly the @default-risky cross-statement ownership
        // move the original analysis flagged: a following labeled statement could then steal a comment that legitimately
        // belongs to the previous statement at some other shape, moving that statement's golden. Per the slice's
        // defer-beats-forcing-green / moving-a-golden rule this last comment is left parked rather than chased.
        drops.put("comment-preservation-labeled-statement @ collapsed",
            "deferred (one residual): a before-label leading line comment (\"Label statement\", 14->13) re-buckets onto"
                + " the PREVIOUS sibling's ForEachStmt own slot under collapse; recovering it needs a cross-statement"
                + " reach that risks moving another statement's @default golden. The between-label-and-body fallback"
                + " (StatementPrinter.recoveredLabeledLeadingComments) already clears \"comment1\" and \"comment2\" fully"
                + " and 13/14 \"Label statement\".");

        // try-resource opener comment @ expanded -- FIXED. The opener comment (try ( // note) was recovered only when it
        // shared the `try (` line (StatementPrinter.tryResourceOpenerComments keyed on startsOnBeginLine(statement)); the
        // expand perturbation pushes the opener onto its own line below the `(` even though the AST is unchanged, so the
        // line-equality filter dropped it. Ownership is now source-order: the opener is the line comment that begins
        // before the first resource, within the `(`-to-first-resource region lineCommentsBeforeFirst already bounds. The
        // per-clause trailing comments (try {} // a) already preserve via the source-order clauseTrailingComment path.
        // Removed from the backlog with that fix.

        // switch -- FIXED (three sub-mechanisms, all source-order ownership; rendering stays line-based).
        //  1. switch-entry-leading-comments @ collapsed dropped "keep first detail": a note stacked before the first
        //     `case` that shares the selector's line is re-bucketed onto the SELECTOR as its own trailing trivia under
        //     collapse. SwitchPrinter.selectorLeadingEntryComments recovers the selector's own/orphan line comments that
        //     lie after the selector and before the first entry (JavaCommentPlacementPolicy.gapLineCommentsBefore) and
        //     feeds them into the existing switch-orphan interleave. At @default the selector owns no such comment (the
        //     notes are switch orphans), so this adds nothing there.
        //  2. switch-statement-rules @ collapsed/expanded dropped the arrow-leading "comment" of a switch rule
        //     (case x -> // comment body): at @default the comment is the body statement's own trivia (COMMENTED_RULE_BODY
        //     renders it), but collapse re-attaches it to the case label expression and expand to the entry orphan bucket.
        //     SwitchPrinter.RECOVERED_COMMENTED_RULE_BODY recovers it via gapLineCommentsBefore over the label and entry
        //     buckets and renders it on its own indented line after `->`, identical to the body-owned shape.
        //  3. switch-statement-rules @ expanded dropped inline case-label block comments "remote"/"hybrid"
        //     (case REMOTE /* remote */, HYBRID): preserved at @default by the raw single-line entry path, but once expand
        //     spreads the entry across lines the structured label renderer rebuilt the comma list from label expressions
        //     only, stripping the comments. SwitchPrinter.commentPreservingCaseLabel rebuilds the label region from its
        //     raw commented token text (CommentedTokenText.tokenLine) and accounts the comments as raw-rendered. Labels
        //     without block comments never enter that path, so @default is unchanged. Removed from the backlog here.

        // comment-complex-block-statements -- comment-complex-block-statements is the dense inline-comment torture
        // fixture; under collapse/expand its many inline block comments (between tokens, inside switch/case, inside
        // loops) are re-attached across constructs. The shape-independent comment-ownership recoveries on this branch
        // (source-order/orphan recovery reusing CommentIndex + JavaCommentPlacementPolicy) cleared every shape-dependent
        // drop except one:
        //  - @collapsed (was "The Heart and the Spade", the enum first-constant leading line comment): FIXED. Collapse
        //    re-buckets that comment from the EnumConstantDeclaration onto its name SimpleName, so EnumConstantComments
        //    .leading (which reads only the declaration's own comment) missed it. EnumConstantComments.firstConstantLeading
        //    now unions the first constant's own leading with JavaCommentPlacementPolicy.lineCommentsBeforeFirst(owner,
        //    first), deduped by comment identity via the claim set, and EnumDeclarationPrinter.formattedEnumEntryList feeds
        //    it as the first constant's leading doc. At @default the comment is the constant's own trivia, so the union
        //    adds the same identity the own path already claimed and the output is unchanged. Removed from the backlog.
        //  - @expanded "is always executed no matter what" (block comment before finally), "at least one iteration !"
        //    (block comment between do-body and while), "Minus One" (trailing block comment on the -1 array element), and
        //    "switch" (the /*switch*/ leading block comment off the switch line): ALL FIXED by the same orphan-recovery
        //    shape. Each owning node's own-comment path renders the comment at @default; when a perturbation re-buckets it
        //    onto the enclosing TryStmt/DoStmt/ArrayInitializerExpr orphan pool (or lifts /*switch*/ onto the line above
        //    the switch keyword), the printer falls back to JavaCommentPlacementPolicy.blockCommentsBefore (or, for the
        //    switch own comment, renders it inline vs own-line by source position). At @default these fallbacks return the
        //    same or empty sets, so output is byte-identical.
        // comment-complex-block-statements @ expanded -- FIXED. The last remaining drop was "overloading", the last
        // parameter's trailing block comment (... int unusedStep /*overloading*/)). The body block owns that comment at
        // both shapes; at @default it sits on the last parameter's line and CallableSignaturePrinter's signature
        // recovery claimed it first, so the body printer never re-emitted it. Expand moved the comment off the
        // parameter's line, defeating the same-line recovery gates (startsAfterNodeOnSameLine), and BlockPrinter does
        // not render a BlockStmt's own comment, so it dropped. The recovery now selects by source order bounded by the
        // parameter list's `)` (startsAfterEndOf(parameter) && startsBefore(closeParen)) instead of same-line, which
        // matches the comment at both shapes while keeping the #20 class-members narrowing: the comment must still
        // begin before `)`, so a next member's leading block comment after `)` is never claimed. At @default the
        // comment begins past the parameter's end column on the same line, so the source-order window is a strict
        // superset of the old same-line window and @default stays byte-identical. Removed from the backlog with that fix.

        // records / enums / conditionals / misc -- the gap-between-siblings ownership predicate is now source-order
        // (CommentIndex.liesBetween), which drained the record-component-spacing and correctness-data-loss perturbations
        // (a gap comment that collapse pushes onto a previous component's line, and a type/name comment that expand
        // re-buckets into the Parameter orphan slot). The entries that remain here are NOT gap-between-siblings: each is
        // a distinct comment-ownership mechanism the perturbation defeats independently of the gap predicate.

        // method-arguments @ expanded -- FIXED (method-chain segment routing, not the gap predicate). The two dropped
        // comments trail arguments of a chained `Stream.concat(...)` whose receiver (`Stream`) sits on its own line.
        // Expand promotes `concat(...)` to the chain root and, because the receiver is on its own line, renders it through
        // MethodCallChainPrinter.brokenPromotedMethodCallRoot, which called the comment-unaware methodCallArgumentList and
        // never recovered the per-argument gap comments. The duplicate `Stream.concat(...)` whose receiver is inline kept
        // both comments through CommentedExpressionListPrinter. brokenPromotedMethodCallRoot now short-circuits through the
        // comment-aware commentedExpressionLists.parenthesized(prefix, expression, arguments) when the argument list
        // carries unclaimed gap comments; parenthesized() returns empty otherwise, so the comment-free path is unchanged.
        // Removed from the backlog with that fix.

        // conditional-expression @ collapsed/expanded -- FIXED. ConditionalExpressionPrinter classified ternary branch
        // comments with token-range column arithmetic that whitespace perturbations defeated. It now classifies each
        // comment (gathered from both the child expressions' own comments and the conditional's orphan comments) by
        // source position relative to the `?`/`:` operator-token positions, and renders both a branch's leading and
        // trailing comment so re-bucketing never drops one. Removed from the backlog with that fix.

        // enum-declaration-layout @ collapsed -- FIXED. The dropped "comment" is the sole comment inside an EMPTY enum
        // body (EmptyEnumWithComment { // comment }); with no constant siblings it is a body orphan only at the expanded
        // shape. Collapsing the body onto the header line makes JavaParser re-attach the comment to the enum name, so
        // getOrphanComments() no longer exposes it and EnumDeclarationPrinter.enumBodyComments dropped it. For an empty
        // body the recovery is now source-order: emptyBodyComments selects the contained line comments that begin after
        // the body's opening brace, which keeps the same comment owned by the body regardless of layout. Removed here.

        // variable-declarations @ collapsed -- FIXED. The two `=`-leading initializer comments were recovered only from
        // the declarator orphan bucket plus the initializer's own comment; under collapse the FIRST comment slides onto
        // the declarator name's line and JavaParser attaches it to the name, which neither bucket reads.
        // VariableInitializerLayout.leadingInitializerComments now also recovers the declarator name's own line comment
        // when it sits in the name-to-initializer gap, selecting purely by source order. Removed from the backlog.

        // class-members @ collapsed -- FIXED. Three `/* TODO(jlevy) */` block comments sit between class members; under
        // collapse a preceding declaration collapses onto one line and CallableSignaturePrinter's trailing-block-comment
        // recovery reached across the parameter list's `)` (via unattachedTrailingBlockComment, which only checks
        // startsAfterNodeOnSameLine) and claimed a comment that belongs to the following member. The broken signature did
        // not render it, so it was claimed-but-dropped. The parameter call site now requires the recovered block comment
        // to begin before the parameter list's closing `)` (trailingBlockCommentPrecedesCloseParen), so it can no longer
        // reach past the signature; the member/block interleaver then renders all three on their own lines. At the default
        // layout the comments are on their own lines, so the same-line recovery matched nothing for them. The narrowing is
        // call-site-local (the shared policy is untouched), so legitimate same-line `param /* note */)` trailing blocks —
        // which begin before `)` — are unaffected, and no record/switch golden moves.

        // interface-declaration @ collapsed -- FIXED. The interface header carries inline block comments, so it routes
        // through the raw escape hatch CommentedInterfacePrinter, whose header rebuild kept only the tokens up to `{`.
        // Under collapse the body's first `// comment` slid onto the brace line (`... { // comment`) and was truncated
        // with the discarded after-brace tokens. formatCommentedInterfaceHeader now returns those after-brace comment
        // tokens separately and the caller carries them onto their own indented body line. At the default layout `{` is
        // the last header token, so the after-brace list is empty and the rendered header is byte-identical.
        return Collections.unmodifiableMap(drops);
    }

    // Accumulators shared across the two parameterized passes; drained by printReport() in @AfterAll for diagnostics.
    private static final Map<String, List<Drop>> GOLDEN_DROPS = new TreeMap<>();
    private static final Map<String, List<Drop>> PERTURBED_DROPS = new TreeMap<>();
    private static final List<String> GOLDEN_EVALUATED = new ArrayList<>();
    private static final List<String> PERTURBED_EVALUATED = new ArrayList<>();

    // ---------------------------------------------------------------------------------------------------------------
    // Pass 1 — golden fixtures, each with its own variant options (default or sidecar), verbatim input.
    // ---------------------------------------------------------------------------------------------------------------

    @ParameterizedTest(name = "{0}")
    @ResourceFixtureSource(glob = "format/**/input.java")
    void goldenFixtureCommentPresence(FormatFixture fixture) {
        if (!parses(fixture.source(), fixture.options())) {
            return; // RECOVER-only inputs: AST/comment comparison is ill-defined, skip (surfaced by count below).
        }
        GOLDEN_EVALUATED.add(fixture.name());
        List<Drop> drops = safeRealDrops(fixture.name(), fixture.source(), fixture.options());
        if (!drops.isEmpty()) {
            GOLDEN_DROPS.put(fixture.name(), drops);
        }
        assertNoUnexpectedDrop(fixture.name(), drops);
    }

    // ---------------------------------------------------------------------------------------------------------------
    // Pass 2 — collapsed / expanded perturbations, default options (mirrors IdempotencePropertyTest exactly).
    // ---------------------------------------------------------------------------------------------------------------

    @ParameterizedTest(name = "{0}")
    @MethodSource("perturbedCorpus")
    void perturbedFixtureCommentPresence(String name, String perturbedSource) {
        FormatterOptions options = FormatterOptions.defaults();
        PERTURBED_EVALUATED.add(name);
        List<Drop> drops = safeRealDrops(name, perturbedSource, options);
        if (!drops.isEmpty()) {
            PERTURBED_DROPS.put(name, drops);
        }
        assertNoUnexpectedDrop(name, drops);
    }

    /**
     * Fails the build when {@code (fixture, shape)} {@code name} drops a comment and is <em>not</em> a documented S9
     * backlog entry. A case that is in {@link #KNOWN_DROPS} but no longer drops anything also fails — a stale exclusion
     * means a fix landed without un-parking it, which would let a future regression hide; remove the entry in the fix's
     * commit.
     */
    private static void assertNoUnexpectedDrop(String name, List<Drop> drops) {
        boolean parked = KNOWN_DROPS.containsKey(name);
        if (!drops.isEmpty()) {
            assertThat(parked)
                    .as("comment-presence net: `%s` drops comment(s) that are not in the documented S9 backlog: %s."
                        + " The formatter must not drop comments — fix the placement/printer, do not add an exclusion.",
                        name, drops)
                    .isTrue();
        } else {
            assertThat(parked)
                    .as("comment-presence net: `%s` is listed in the S9 backlog (KNOWN_DROPS) but no longer drops a"
                        + " comment. A fix landed without un-parking it; remove its KNOWN_DROPS entry so the net guards"
                        + " the case again.", name)
                    .isFalse();
        }
    }

    /**
     * Two parse-preserving whitespace perturbations of each golden fixture input, default options — the same corpus
     * {@code IdempotencePropertyTest.perturbedCorpus} feeds, so the cases here line up 1:1 with the ones the guardrail
     * flagged. A perturbation that fails to parse under default options is dropped (it is not a comparable case).
     */
    static Stream<Arguments> perturbedCorpus() {
        FormatterOptions defaults = FormatterOptions.defaults();
        List<Arguments> arguments = new ArrayList<>();
        for (FixtureInput fixture : ResourceFixtureSource.Provider.inputs("format/**/input.java")) {
            for (SourceShapePerturbation.Shape shape : SourceShapePerturbation.Shape.values()) {
                String perturbed = SourceShapePerturbation.perturb(fixture.source(), shape);
                String shapeName = shape == SourceShapePerturbation.Shape.COLLAPSE ? "collapsed" : "expanded";
                String name = fixture.name() + " @ " + shapeName;
                if (perturbed != null && parses(perturbed, defaults)) {
                    arguments.add(Arguments.of(name, perturbed));
                }
            }
        }
        return arguments.stream();
    }

    // ---------------------------------------------------------------------------------------------------------------
    // Comparator positive controls — prove the net actually bites and that its normalization is not over-tolerant.
    // ---------------------------------------------------------------------------------------------------------------

    /**
     * The comparator detects a genuine drop. Rather than rely on a particular formatter bug to manufacture a drop (those
     * get fixed), this feeds the pure comparator an {@code output} that is the input with one comment deleted, and
     * asserts that exact content is reported missing. If this ever returns empty, the output-level net has gone blind
     * and would no longer catch data loss.
     */
    @org.junit.jupiter.api.Test
    void comparatorReportsDropWhenAnInputCommentIsAbsentFromOutput() {
        String input = """
            class Demo {
                // keep me
                int present; // also keep
                int gone; // DROP-ME-marker
            }
            """;
        String outputMissingOneComment = """
            class Demo {
                // keep me
                int present; // also keep
                int gone;
            }
            """;
        List<Drop> drops = realDrops(input, outputMissingOneComment, FormatterOptions.defaults());
        assertThat(drops)
                .as("comparator must report the deleted comment as a drop; an empty result means the net is blind")
                .extracting(Drop::content)
                .contains("DROP-ME-marker");
    }

    /**
     * The comparator does <em>not</em> false-positive on the formatter's legitimate comment re-shaping. A block comment
     * whose body the formatter re-indents and whose lines it re-aligns under a {@code *} prefix carries the same words;
     * normalization must treat it as present, not dropped — otherwise the net would flag every reflowed comment.
     */
    @org.junit.jupiter.api.Test
    void comparatorIgnoresLegitimateReshapingOfAPreservedComment() {
        String reshaped = """
            class Demo {
                            // a line comment with odd indentation that the formatter re-indents
                void method() {
                /*
                 a block comment
                 the formatter re-aligns
                 */
                    int x = 1;
                }
            }
            """;
        assertThat(realDrops(reshaped, FormatterOptions.defaults()))
                .as("re-indentation / *-prefix re-alignment of a preserved comment must not read as a drop")
                .isEmpty();
    }

    // ---------------------------------------------------------------------------------------------------------------
    // Report
    // ---------------------------------------------------------------------------------------------------------------

    @AfterAll
    static void printReport() {
        System.out.println("\n================ COMMENT-PRESENCE DIAGNOSTIC ================");
        System.out.println("golden cases evaluated:    " + GOLDEN_EVALUATED.size());
        System.out.println("perturbed cases evaluated: " + PERTURBED_EVALUATED.size());

        System.out.println("\n---- REAL DROPS: golden fixtures (verbatim input, fixture's own options) ----");
        if (GOLDEN_DROPS.isEmpty()) {
            System.out.println("  (none)");
        }
        GOLDEN_DROPS.forEach((name, drops) -> {
            System.out.println("  FIXTURE " + name);
            drops.forEach(drop -> System.out.println("      DROP " + drop));
        });

        System.out.println("\n---- REAL DROPS: perturbations (collapsed/expanded, default options) ----");
        if (PERTURBED_DROPS.isEmpty()) {
            System.out.println("  (none)");
        }
        PERTURBED_DROPS.forEach((name, drops) -> {
            System.out.println("  PERTURBED " + name);
            drops.forEach(drop -> System.out.println("      DROP " + drop));
        });

        System.out.println("\n---- SUMMARY (grep-friendly) ----");
        System.out.println("REALDROP-GOLDEN-COUNT " + GOLDEN_DROPS.size());
        System.out.println("REALDROP-PERTURBED-COUNT " + PERTURBED_DROPS.size());
        GOLDEN_DROPS.keySet().forEach(key -> System.out.println("REALDROP-GOLDEN " + key));
        PERTURBED_DROPS.keySet().forEach(key -> System.out.println("REALDROP-PERTURBED " + key));
        System.out.println("============== END COMMENT-PRESENCE DIAGNOSTIC ==============\n");
    }

    // ---------------------------------------------------------------------------------------------------------------
    // Comparator core
    // ---------------------------------------------------------------------------------------------------------------

    /** A single dropped comment content together with the input locations it appeared at. */
    record Drop(String content, int inputCount, int outputCount, List<String> inputLocations) {
        @Override
        public String toString() {
            String oneLine = content.replace("\n", "\\n");
            if (oneLine.length() > 140) {
                oneLine = oneLine.substring(0, 137) + "...";
            }
            return "[in=" + inputCount + " out=" + outputCount + " @" + inputLocations + "] \"" + oneLine + "\"";
        }
    }

    /**
     * Returns the comment contents whose multiplicity in the output is strictly lower than in the input — i.e. genuine
     * comment-data-loss. Empty when no content is lost. Normalization (see {@link #normalizeRawComment}) makes
     * re-indentation / trailing-whitespace / block re-shaping invisible, so only genuine absence counts.
     *
     * <p><strong>The lexer token stream is the ground truth for presence.</strong> The drop multiset is computed by
     * counting comment <em>tokens</em> directly from JavaParser's lexer ({@link #lexerCommentCounts}) on the input and
     * on the formatted output. A lexer count cannot phantom-drop or phantom-gain: it counts the actual {@code //} and
     * {@code /* *}{@code /} tokens present in the source bytes. This deliberately does <em>not</em> use
     * {@code getAllContainedComments()} as the primary signal, because that attributed-comment traversal has the same
     * weakness the guardrail does — it can list one {@code Comment} instance twice (manufacturing a phantom drop after
     * reflow) and can omit a comment that survives in the text but attaches where the traversal does not reach (e.g. a
     * leading comment between a {@code package} declaration and the first type, which is present in the output yet absent
     * from {@code getAllContainedComments()}). Both failure modes were observed and would corrupt an AST-primary count.
     *
     * <p>The AST is still parsed, but only to attach best-effort <em>input locations</em> to each dropped content for the
     * report; if the AST cannot locate a dropped content (the omitted-orphan case), the drop is still reported, with an
     * empty location list. A {@code [XCHECK]} line is printed whenever the AST-derived drop magnitude disagrees with the
     * authoritative lexer magnitude, so the divergence between the two witnesses stays visible rather than hidden.
     */
    static List<Drop> realDrops(String source, FormatterOptions options) {
        return realDrops(source, Frmtr.format(source, options), options);
    }

    /**
     * Pure comparator over an arbitrary (input, output) pair, factored out of {@link #realDrops(String,
     * FormatterOptions)} so the comparator itself can be exercised in isolation (feeding a deliberately comment-stripped
     * output) without depending on any particular formatter bug to manufacture a drop.
     */
    static List<Drop> realDrops(String source, String formatted, FormatterOptions options) {
        Map<String, Integer> lexerInput = lexerCommentCounts(source);
        Map<String, Integer> lexerOutput = lexerCommentCounts(formatted);

        // Best-effort AST locations for reporting only; never used to decide whether something dropped.
        Map<String, List<String>> inputLocations = astLocationsByContent(source, options);
        Map<String, Integer> astInput = astCommentCounts(source, options);
        Map<String, Integer> astOutput = astCommentCounts(formatted, options);

        List<Drop> drops = new ArrayList<>();
        for (Map.Entry<String, Integer> entry : lexerInput.entrySet()) {
            String content = entry.getKey();
            int in = entry.getValue();
            int out = lexerOutput.getOrDefault(content, 0);
            int astDrop = astInput.getOrDefault(content, 0) - astOutput.getOrDefault(content, 0);
            if (out < in) {
                drops.add(new Drop(content, in, out, inputLocations.getOrDefault(content, List.of())));
                if (astDrop != in - out) {
                    // AST UNDER-reports a real drop (e.g. an omitted file-leading orphan the traversal never reaches).
                    System.out.println("  [XCHECK] AST under-reports \"" + content.replace("\n", "\\n")
                        + "\": lexer-drop=" + (in - out) + " ast-drop=" + astDrop
                        + " — AST traversal artifact, lexer authoritative (this case IS a real drop)");
                }
            } else if (astDrop > 0) {
                // AST OVER-reports: it counts a drop the lexer (ground truth) refutes — the text is present. This is the
                // guardrail's own failure mode reproduced at the AST level; the case is correctly NOT recorded as a drop.
                System.out.println("  [XCHECK] AST over-reports (NOT a real drop) \"" + content.replace("\n", "\\n")
                    + "\": ast-drop=" + astDrop + " but lexer in=" + in + " out=" + out
                    + " (text present) — accounting gap, excluded from drops");
            }
        }
        return drops;
    }

    private static Map<String, Integer> astCommentCounts(String source, FormatterOptions options) {
        return multiset(commentEntries(parse(source, options)));
    }

    private static Map<String, List<String>> astLocationsByContent(String source, FormatterOptions options) {
        Map<String, List<String>> locations = new LinkedHashMap<>();
        for (CommentEntry entry : commentEntries(parse(source, options))) {
            locations.computeIfAbsent(entry.content(), key -> new ArrayList<>()).add(entry.location());
        }
        return locations;
    }

    /**
     * Counts each comment token's normalized content directly from the lexer stream, ignoring the attributed-comment
     * AST entirely. This is the authoritative presence witness used by {@link #realDrops}: a lexer count cannot
     * phantom-drop or phantom-gain, because it counts the actual comment tokens in the source bytes.
     */
    private static Map<String, Integer> lexerCommentCounts(String source) {
        Map<String, Integer> counts = new LinkedHashMap<>();
        TokenRange tokens = parseResultBleedingEdge(source).getResult()
                .flatMap(CompilationUnit::getTokenRange)
                .orElse(null);
        if (tokens == null) {
            return counts;
        }
        for (JavaToken token : tokens) {
            if (token.getCategory().isComment()) {
                counts.merge(normalizeRawComment(token.getText()), 1, Integer::sum);
            }
        }
        return counts;
    }

    /** Normalizes a raw comment token's text the same way {@link #normalize} normalizes an attributed comment. */
    private static String normalizeRawComment(String raw) {
        String text = raw.strip();
        if (text.startsWith("//")) {
            return text.substring(2).strip();
        }
        String inner = text;
        if (inner.startsWith("/*")) {
            inner = inner.substring(2);
        }
        if (inner.endsWith("*/")) {
            inner = inner.substring(0, inner.length() - 2);
        }
        List<String> lines = new ArrayList<>();
        for (String rawLine : inner.split("\n", -1)) {
            String line = rawLine.strip();
            if (line.startsWith("*")) {
                line = line.substring(1).strip();
            }
            if (!line.isEmpty()) {
                lines.add(line);
            }
        }
        return String.join("\n", lines);
    }

    private static List<Drop> safeRealDrops(String name, String source, FormatterOptions options) {
        try {
            return realDrops(source, options);
        } catch (RuntimeException exception) {
            System.out.println("  [WARN] could not evaluate " + name + ": " + exception.getMessage());
            return List.of();
        }
    }

    private record CommentEntry(String content, String location) {}

    private static List<CommentEntry> commentEntries(CompilationUnit unit) {
        List<CommentEntry> entries = new ArrayList<>();
        // Dedupe by JavaParser object identity. getAllContainedComments() can list the SAME Comment instance twice when
        // it is reachable through more than one traversal path (verified: an enum-constant trailing comment appears twice
        // in the input tree but once in the reflowed output tree). That double-listing is a parser-traversal artifact,
        // not a second copy of the text, so counting it would manufacture phantom drops. Two DISTINCT Comment instances
        // carrying the same text (e.g. two separate `/*dead code*/` comments) are kept separate — only reference-equal
        // duplicates collapse — so genuine multiplicity drops are preserved.
        Set<Comment> seen = Collections.newSetFromMap(new IdentityHashMap<>());
        for (Comment comment : unit.getAllContainedComments()) {
            if (!seen.add(comment)) {
                continue;
            }
            String location = comment.getRange()
                    .map(range -> "L" + range.begin.line + ":C" + range.begin.column)
                    .orElse("L?");
            entries.add(new CommentEntry(normalize(comment), location));
        }
        return entries;
    }

    private static Map<String, Integer> multiset(List<CommentEntry> entries) {
        Map<String, Integer> counts = new LinkedHashMap<>();
        for (CommentEntry entry : entries) {
            counts.merge(entry.content(), 1, Integer::sum);
        }
        return counts;
    }

    /**
     * Normalizes a comment's content so legitimate formatter re-shaping does not read as a difference:
     *
     * <ul>
     *   <li>line comment: text after {@code //}, {@link String#strip stripped};
     *   <li>block / javadoc: inner text split into lines, each line's leading whitespace and a single optional leading
     *       {@code *} removed and trailing whitespace stripped, blank lines dropped, non-blank lines joined with
     *       {@code \n}. Dropping blank interior lines is deliberate — the formatter may add/remove blank lines inside a
     *       block body without losing author text, and we only want to detect genuine absence of words.
     * </ul>
     */
    private static String normalize(Comment comment) {
        String content = comment.getContent();
        if (comment.isLineComment()) {
            return content.strip();
        }
        List<String> lines = new ArrayList<>();
        for (String rawLine : content.split("\n", -1)) {
            String line = rawLine.strip();
            if (line.startsWith("*")) {
                line = line.substring(1).strip();
            }
            if (!line.isEmpty()) {
                lines.add(line);
            }
        }
        return String.join("\n", lines);
    }

    // ---------------------------------------------------------------------------------------------------------------
    // Parsing — match the formatter's configuration (FormatterGuardrails / JavaFormatter).
    // ---------------------------------------------------------------------------------------------------------------

    private static CompilationUnit parse(String source, FormatterOptions options) {
        ParseResult<CompilationUnit> result = newParser(options)
                .parse(ParseStart.COMPILATION_UNIT, Providers.provider(source));
        return result.getResult()
                .orElseThrow(() -> new IllegalStateException("diagnostic parse failed: " + result.getProblems()));
    }

    private static boolean parses(String source, FormatterOptions options) {
        return newParser(options).parse(ParseStart.COMPILATION_UNIT, Providers.provider(source)).isSuccessful();
    }

    private static JavaParser newParser(FormatterOptions options) {
        return new JavaParser(new ParserConfiguration()
                .setLanguageLevel(languageLevel(options))
                .setStoreTokens(true)
                .setAttributeComments(true));
    }

    /** Mirror JavaFormatter.javaParserLanguageLevel so the diagnostic parse matches the formatter's parse exactly. */
    private static ParserConfiguration.LanguageLevel languageLevel(FormatterOptions options) {
        return switch (options.javaLanguageLevel()) {
            case UNSET -> null;
            case LATEST_AVAILABLE -> ParserConfiguration.LanguageLevel.BLEEDING_EDGE;
            case JAVA_8 -> ParserConfiguration.LanguageLevel.JAVA_8;
            case JAVA_9 -> ParserConfiguration.LanguageLevel.JAVA_9;
            case JAVA_10 -> ParserConfiguration.LanguageLevel.JAVA_10;
            case JAVA_11 -> ParserConfiguration.LanguageLevel.JAVA_11;
            case JAVA_12 -> ParserConfiguration.LanguageLevel.JAVA_12;
            case JAVA_13 -> ParserConfiguration.LanguageLevel.JAVA_13;
            case JAVA_14 -> ParserConfiguration.LanguageLevel.JAVA_14;
            case JAVA_15 -> ParserConfiguration.LanguageLevel.JAVA_15;
            case JAVA_16 -> ParserConfiguration.LanguageLevel.JAVA_16;
            case JAVA_17 -> ParserConfiguration.LanguageLevel.JAVA_17;
            case JAVA_18 -> ParserConfiguration.LanguageLevel.JAVA_18;
            case JAVA_19 -> ParserConfiguration.LanguageLevel.JAVA_19;
            case JAVA_20 -> ParserConfiguration.LanguageLevel.JAVA_20;
            case JAVA_21 -> ParserConfiguration.LanguageLevel.JAVA_21;
            case JAVA_22 -> ParserConfiguration.LanguageLevel.JAVA_22;
            case JAVA_23 -> ParserConfiguration.LanguageLevel.JAVA_23;
            case JAVA_24 -> ParserConfiguration.LanguageLevel.JAVA_24;
            case JAVA_25 -> ParserConfiguration.LanguageLevel.JAVA_25;
        };
    }

    // ---------------------------------------------------------------------------------------------------------------
    // Lexer parse for the comment-token ground truth. The corpus perturbation itself lives in SourceShapePerturbation,
    // shared with IdempotencePropertyTest so both tests re-shape the corpus identically.
    // ---------------------------------------------------------------------------------------------------------------

    private static ParseResult<CompilationUnit> parseResultBleedingEdge(String source) {
        return new JavaParser(new ParserConfiguration()
                .setLanguageLevel(ParserConfiguration.LanguageLevel.BLEEDING_EDGE)
                .setStoreTokens(true)
                .setAttributeComments(true))
                .parse(ParseStart.COMPILATION_UNIT, Providers.provider(source));
    }
}
