package dev.lanwen.frmtr;

import static org.assertj.core.api.Assertions.assertThat;

import com.github.javaparser.JavaParser;
import com.github.javaparser.JavaToken;
import com.github.javaparser.ParseResult;
import com.github.javaparser.ParseStart;
import com.github.javaparser.ParserConfiguration;
import com.github.javaparser.Providers;
import com.github.javaparser.TokenRange;
import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.comments.Comment;
import java.util.ArrayList;
import java.util.Collections;
import java.util.IdentityHashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;
import java.util.stream.Stream;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

/**
 * Output-level comment-presence net — the CI gate for "the formatter never drops a comment" (roadmap S7 part 2;
 * promoted from the {@code inv/comment-presence} diagnostic).
 *
 * <p><strong>Why this is the gate and {@code assertAllCommentsAccounted} is not.</strong> The accounting guardrail
 * flags a comment when it was not <em>registered</em> in the formatter's claimed / raw-accounted sets. That
 * registration is keyed on JavaParser {@link Comment} object identity, so it is a <em>proxy</em> for "did the comment's
 * text reach the output", not a measurement of it: a comment rendered through a path that never records accounting, or
 * recorded under a different comment identity, is flagged even though its text is present (over-reports), and an
 * AST-invisible orphan it never traverses is missed (under-reports). This net answers the real question directly: it
 * compares the <em>lexer comment-token multiset</em> of the INPUT against that of the {@link Frmtr#format formatted
 * OUTPUT}, and fails when any input comment content appears fewer times in the output than in the input. The lexer
 * count is ground truth — it counts the actual {@code //} and {@code /* *}{@code /} tokens in the source bytes, so it
 * cannot phantom-drop or phantom-gain the way an attributed-comment traversal can.
 *
 * <p><strong>What it asserts, over what corpus.</strong> Two parameterized passes fail on any non-excluded
 * {@code (fixture, shape)} that drops a comment: (1) every golden fixture input at its own variant options, verbatim;
 * (2) collapsed/expanded whitespace perturbations of every golden input at default options, generated by the shared
 * {@link SourceShapePerturbation} engine that {@code IdempotencePropertyTest} also uses (so a comment dropped only when
 * the layout moves is still caught — that shape-dependent ownership is the B1 thesis). Tolerant normalization (see
 * {@link #normalizeRawComment}) makes
 * re-indentation, trailing-whitespace strip, and block {@code *}-prefix re-shaping invisible, so only genuine textual
 * <em>absence</em> fails.
 *
 * <p><strong>The exclusion list ({@link #KNOWN_DROPS}) is the S9 backlog.</strong> It is seeded with exactly the
 * {@code (fixture, shape)} cases that drop a comment on this branch today, each annotated with the dropped text and a
 * pointer to the S9 cluster that owns the fix. This makes the net green now while it bites on any <em>new</em> drop
 * immediately. As each S9 cluster lands a real fix, its entries are removed here in the same change; the net is fully
 * green with an empty exclusion list when S9 completes. The exclusion list is never widened to mask a regression — a
 * new drop outside the backlog must be fixed or diagnosed, not parked (see the class's STOP conditions in
 * {@code docs/proposals/comment-data-loss.md}).
 *
 * <p>{@link #printReport()} still drains a full per-drop inventory to stdout as a development aid; the build outcome is
 * decided by the per-case assertions, not the report.
 */
final class CommentPresenceDiagnosticTest {

    /**
     * The S9 comment-drop backlog: {@code (fixture, shape)} display names whose formatting still drops a comment on this
     * branch, each kept out of the asserting net until its fix lands.
     *
     * <p>Each entry's value records the comment text(s) the fixture loses and the work the fix belongs to, so the parked
     * finding stays honest and reviewable. The remaining entries fall into two buckets, both documented per-entry:
     *
     * <ul>
     *   <li><strong>needs B1</strong> — source-shape consolidation. The comment is dropped only when the whitespace
     *       perturbation moves it off the source line/column its ownership recovery keys on (or JavaParser re-attributes
     *       it across constructs under collapse). These are the headline evidence for the B1 {@code SourceShapePolicy};
     *       a shape-independent fix is the policy consolidation, not a local printer patch.
     *   <li><strong>needs B2</strong> — deterministic, attachment-independent comment ownership. The Guava copyright
     *       file-header has an empty AST attachment ({@code getAllContainedComments} never returns it), so no
     *       attachment-based path can reach it.
     * </ul>
     *
     * <p>The structural drops that did <em>not</em> depend on incidental layout — comments orphaned between top-level
     * types, before a {@code case}, around a single text-block argument, trailing a block's last statement or a call's
     * last argument, and an inline block comment between an annotation and its member — are fixed and removed from this
     * list (see the branch's per-cluster commits).
     *
     * <p><strong>Do not add entries to silence a regression.</strong> This list only ever shrinks. A drop on a case not
     * already here is a new data-loss bug the net is meant to catch.
     */
    private static final Map<String, String> KNOWN_DROPS = knownDrops();

    private static Map<String, String> knownDrops() {
        Map<String, String> drops = new TreeMap<>();

        // -- P1: drops only when whitespace is perturbed; shape-dependent ownership (B1 evidence). --

        // control-condition / if -- ESCALATED to B1 (source-shape consolidation). Under whole-fixture collapse the line
        // comments inside/after a control condition are mis-attributed by JavaParser across method boundaries (a comment
        // from one method's switch selector bled into another method's body), so the loss is in attachment, not in a
        // single printer's adjacency check. A shape-independent fix needs the B1 SourceShapePolicy, not a local patch.
        drops.put("comment-preservation-control-condition @ collapsed",
            "needs B1: \"keep polling until the route snapshot is visible\","
                + " \"use the normalized event kind for routing\"");
        drops.put("comment-preservation-control-condition @ expanded",
            "needs B1: \"keep polling until the route snapshot is visible\","
                + " \"read selector after cursor state is refreshed\","
                + " \"keep the body delayed until route state is stable\","
                + " \"keep selector comment outside the condition\", \"use the normalized event kind for routing\"");
        drops.put("comment-preservation-if-statement @ collapsed",
            "needs B1 (control-condition/if): \"test\" (12->9),"
                + " \"https://docs.example.invalid/token-envelope-03.html\"");
        drops.put("comment-preservation-if-statement @ expanded",
            "needs B1 (control-condition/if): \"test\" (12->7), \"comment\","
                + " \"legacy key envelope before registry draft 04\","
                + " \"https://docs.example.invalid/token-envelope-03.html\","
                + " \"keep manual routing while backfill catches up\"");

        // labeled-statement -- needs B1. Under whole-fixture collapse the labeled-statement leading comments are
        // mis-attributed en masse (comment1 22->6), the same source-shape attachment failure as control-condition.
        drops.put("comment-preservation-labeled-statement @ collapsed",
            "needs B1 (labeled-statement): \"Label statement\" (14->4), \"comment1\" (22->6), \"comment2\" (14->4)");

        // try-resource -- needs B1. The try-resource opener comment (try ( // note) and the per-clause trailing
        // comments (try {} // a) are recovered from source-position scans that the expand perturbation defeats by
        // moving the comment off the try/clause line; reconciling all of opener/leading/gap/trailing shape-independently
        // is the B1 SourceShapePolicy consolidation rather than a local printer patch.
        drops.put("comment-preservation-try-resources @ expanded",
            "needs B1 (try-resource): \"resource scope {\", \"single resource scope {\" (opener comment after `(`)");
        drops.put("try-resource-layout @ expanded",
            "needs B1 (try-resource): \"a\", \"b\", \"c\", \"a2\", \"b2\", \"c2\" (per-clause try/catch/finally trailing"
                + " comments)");

        // method-arguments -- needs B1. The remaining @ expanded drops are gap comments between arguments that move
        // off their anchor line under expand; the trailing-argument case is fixed (block-orphan-method-call-comments).
        drops.put("comment-preservation-method-arguments @ expanded",
            "needs B1 (method-arguments): \"services selected directly\", \"services selected by scaling\"");

        // switch -- entry-leading comments stacked before a `case` are now interleaved from the switch's orphan comments;
        // these two remain because a leading comment JavaParser mis-attaches to the SELECTOR under collapse (not a switch
        // orphan) is still dropped, and switch-statement-rules also drops inline block comments inside a case label
        // (case REMOTE /* remote */, HYBRID). Both are narrower follow-ups on top of the interleave landed here.
        drops.put("switch-entry-leading-comments @ collapsed",
            "S9 backlog (switch): \"keep first detail\" (selector-attached under collapse; the other three now preserved)");
        drops.put("switch-statement-rules @ collapsed", "S9 backlog (switch): \"comment\" (3->0)");
        drops.put("switch-statement-rules @ expanded",
            "S9 backlog (switch): inline case-label block comments \"remote\", \"hybrid\"; \"comment\""
                + " (leading \"default case\"/\"case c\"/\"fall through\" now preserved)");

        // block-comment / annotation gap -- needs B1. comment-complex-block-statements is the dense inline-comment
        // torture fixture; under collapse/expand its many inline block comments (between tokens, inside switch/case,
        // inside loops) are re-attached across constructs. block-comment-shapes loses a `/*a*/` whose ownership flips
        // with layout. These are the source-shape attachment problem at its most concentrated.
        drops.put("comment-complex-block-statements @ collapsed",
            "needs B1 (block/annotation gap): \"switch\", \"dead code\", \"The Heart and the Spade\"");
        drops.put("comment-complex-block-statements @ expanded",
            "needs B1 (block/annotation gap): \"is always executed no matter what\", \"Minus One\", \"switch\","
                + " \"overloading\", \"at least one iteration !\", \"Additionnal enumeration\"");
        drops.put("comment-preservation-block-comment-shapes @ collapsed",
            "needs B1 (block/annotation gap): \"a\" (3->2)");

        // records / enums / conditionals / misc -- needs B1. Each loses a comment whose anchor moves under perturbation:
        // a leading comment between `=` and an initializer (variable-declarations), a comment between a record
        // component's type and name (correctness-data-loss), an empty-enum-body comment, a ternary-branch comment, and
        // record-component leading comments. All are position-anchored recoveries the perturbation defeats.
        drops.put("record-component-spacing @ collapsed", "needs B1 (records/enums/misc): \"comment\" (2->1)");
        drops.put("record-component-spacing @ expanded", "needs B1 (records/enums/misc): \"comment\" (2->1)");
        drops.put("enum-declaration-layout @ collapsed", "needs B1 (records/enums/misc): \"comment\" (3->2)");
        drops.put("conditional-expression-space-indentation @ collapsed",
            "needs B1 (records/enums/misc): \"c\" (4->3)");
        drops.put("conditional-expression-space-indentation @ expanded",
            "needs B1 (records/enums/misc): \"b\" (4->0), \"c\" (4->1)");
        drops.put("correctness-data-loss @ expanded",
            "needs B1 (records/enums/misc): \"keep this comment with the type\" (between record-component type and name)");
        drops.put("variable-declarations @ collapsed",
            "needs B1 (records/enums/misc): \"there is a random comment on this line up here\" (initializer-leading"
                + " comment lost when the declaration collapses onto one line)");

        // class-members / interface (guardrail-missed; found only by the lexer net)
        // class-members @ expanded loses the Guava copyright FILE HEADER, which has an empty AST attachment
        // (getAllContainedComments never returns it): this is the B2 orphan-ownership case, not reachable by any
        // attachment-based path. The @ collapsed TODO(jlevy) blocks and the interface `// comment` are B1 (member-block
        // / interface-body comment ownership that the perturbation re-anchors).
        drops.put("comment-preservation-class-members @ collapsed",
            "needs B1 (class-members): three \"TODO(jlevy): ...\" block comments");
        drops.put("comment-preservation-class-members @ expanded",
            "needs B2 (class-members): the Guava copyright file-header block (AST-invisible orphan,"
                + " getAllContainedComments never returns it)");
        drops.put("comment-preservation-interface-declaration @ collapsed",
            "needs B1 (interface-declaration): \"comment\" (interface-body leading comment)");

        return Collections.unmodifiableMap(drops);
    }

    // Accumulators shared across the two parameterized passes; drained by printReport() in @AfterAll for diagnostics.
    private static final Map<String, List<Drop>> GOLDEN_DROPS = new TreeMap<>();
    private static final Map<String, List<Drop>> PERTURBED_DROPS = new TreeMap<>();
    private static final List<String> GOLDEN_EVALUATED = new ArrayList<>();
    private static final List<String> PERTURBED_EVALUATED = new ArrayList<>();

    // ---------------------------------------------------------------------------------------------------------------
    // Pass 1 — golden fixtures, each with its own variant options (default or sidecar), verbatim input.
    // ---------------------------------------------------------------------------------------------------------------

    @ParameterizedTest(name = "{0}")
    @ResourceFixtureSource(glob = "format/**/input.java")
    void goldenFixtureCommentPresence(FormatFixture fixture) {
        if (!parses(fixture.source(), fixture.options())) {
            return; // RECOVER-only inputs: AST/comment comparison is ill-defined, skip (surfaced by count below).
        }
        GOLDEN_EVALUATED.add(fixture.name());
        List<Drop> drops = safeRealDrops(fixture.name(), fixture.source(), fixture.options());
        if (!drops.isEmpty()) {
            GOLDEN_DROPS.put(fixture.name(), drops);
        }
        assertNoUnexpectedDrop(fixture.name(), drops);
    }

    // ---------------------------------------------------------------------------------------------------------------
    // Pass 2 — collapsed / expanded perturbations, default options (mirrors IdempotencePropertyTest exactly).
    // ---------------------------------------------------------------------------------------------------------------

    @ParameterizedTest(name = "{0}")
    @MethodSource("perturbedCorpus")
    void perturbedFixtureCommentPresence(String name, String perturbedSource) {
        FormatterOptions options = FormatterOptions.defaults();
        PERTURBED_EVALUATED.add(name);
        List<Drop> drops = safeRealDrops(name, perturbedSource, options);
        if (!drops.isEmpty()) {
            PERTURBED_DROPS.put(name, drops);
        }
        assertNoUnexpectedDrop(name, drops);
    }

    /**
     * Fails the build when {@code (fixture, shape)} {@code name} drops a comment and is <em>not</em> a documented S9
     * backlog entry. A case that is in {@link #KNOWN_DROPS} but no longer drops anything also fails — a stale exclusion
     * means a fix landed without un-parking it, which would let a future regression hide; remove the entry in the fix's
     * commit.
     */
    private static void assertNoUnexpectedDrop(String name, List<Drop> drops) {
        boolean parked = KNOWN_DROPS.containsKey(name);
        if (!drops.isEmpty()) {
            assertThat(parked)
                    .as("comment-presence net: `%s` drops comment(s) that are not in the documented S9 backlog: %s."
                        + " The formatter must not drop comments — fix the placement/printer, do not add an exclusion.",
                        name, drops)
                    .isTrue();
        } else {
            assertThat(parked)
                    .as("comment-presence net: `%s` is listed in the S9 backlog (KNOWN_DROPS) but no longer drops a"
                        + " comment. A fix landed without un-parking it; remove its KNOWN_DROPS entry so the net guards"
                        + " the case again.", name)
                    .isFalse();
        }
    }

    /**
     * Two parse-preserving whitespace perturbations of each golden fixture input, default options — the same corpus
     * {@code IdempotencePropertyTest.perturbedCorpus} feeds, so the cases here line up 1:1 with the ones the guardrail
     * flagged. A perturbation that fails to parse under default options is dropped (it is not a comparable case).
     */
    static Stream<Arguments> perturbedCorpus() {
        FormatterOptions defaults = FormatterOptions.defaults();
        List<Arguments> arguments = new ArrayList<>();
        for (FixtureInput fixture : ResourceFixtureSource.Provider.inputs("format/**/input.java")) {
            for (SourceShapePerturbation.Shape shape : SourceShapePerturbation.Shape.values()) {
                String perturbed = SourceShapePerturbation.perturb(fixture.source(), shape);
                String shapeName = shape == SourceShapePerturbation.Shape.COLLAPSE ? "collapsed" : "expanded";
                String name = fixture.name() + " @ " + shapeName;
                if (perturbed != null && parses(perturbed, defaults)) {
                    arguments.add(Arguments.of(name, perturbed));
                }
            }
        }
        return arguments.stream();
    }

    // ---------------------------------------------------------------------------------------------------------------
    // Comparator positive controls — prove the net actually bites and that its normalization is not over-tolerant.
    // ---------------------------------------------------------------------------------------------------------------

    /**
     * The comparator detects a genuine drop. Rather than rely on a particular formatter bug to manufacture a drop (those
     * get fixed), this feeds the pure comparator an {@code output} that is the input with one comment deleted, and
     * asserts that exact content is reported missing. If this ever returns empty, the output-level net has gone blind
     * and would no longer catch data loss.
     */
    @org.junit.jupiter.api.Test
    void comparatorReportsDropWhenAnInputCommentIsAbsentFromOutput() {
        String input = """
            class Demo {
                // keep me
                int present; // also keep
                int gone; // DROP-ME-marker
            }
            """;
        String outputMissingOneComment = """
            class Demo {
                // keep me
                int present; // also keep
                int gone;
            }
            """;
        List<Drop> drops = realDrops(input, outputMissingOneComment, FormatterOptions.defaults());
        assertThat(drops)
                .as("comparator must report the deleted comment as a drop; an empty result means the net is blind")
                .extracting(Drop::content)
                .contains("DROP-ME-marker");
    }

    /**
     * The comparator does <em>not</em> false-positive on the formatter's legitimate comment re-shaping. A block comment
     * whose body the formatter re-indents and whose lines it re-aligns under a {@code *} prefix carries the same words;
     * normalization must treat it as present, not dropped — otherwise the net would flag every reflowed comment.
     */
    @org.junit.jupiter.api.Test
    void comparatorIgnoresLegitimateReshapingOfAPreservedComment() {
        String reshaped = """
            class Demo {
                            // a line comment with odd indentation that the formatter re-indents
                void method() {
                /*
                 a block comment
                 the formatter re-aligns
                 */
                    int x = 1;
                }
            }
            """;
        assertThat(realDrops(reshaped, FormatterOptions.defaults()))
                .as("re-indentation / *-prefix re-alignment of a preserved comment must not read as a drop")
                .isEmpty();
    }

    // ---------------------------------------------------------------------------------------------------------------
    // Report
    // ---------------------------------------------------------------------------------------------------------------

    @AfterAll
    static void printReport() {
        System.out.println("\n================ COMMENT-PRESENCE DIAGNOSTIC ================");
        System.out.println("golden cases evaluated:    " + GOLDEN_EVALUATED.size());
        System.out.println("perturbed cases evaluated: " + PERTURBED_EVALUATED.size());

        System.out.println("\n---- REAL DROPS: golden fixtures (verbatim input, fixture's own options) ----");
        if (GOLDEN_DROPS.isEmpty()) {
            System.out.println("  (none)");
        }
        GOLDEN_DROPS.forEach((name, drops) -> {
            System.out.println("  FIXTURE " + name);
            drops.forEach(drop -> System.out.println("      DROP " + drop));
        });

        System.out.println("\n---- REAL DROPS: perturbations (collapsed/expanded, default options) ----");
        if (PERTURBED_DROPS.isEmpty()) {
            System.out.println("  (none)");
        }
        PERTURBED_DROPS.forEach((name, drops) -> {
            System.out.println("  PERTURBED " + name);
            drops.forEach(drop -> System.out.println("      DROP " + drop));
        });

        System.out.println("\n---- SUMMARY (grep-friendly) ----");
        System.out.println("REALDROP-GOLDEN-COUNT " + GOLDEN_DROPS.size());
        System.out.println("REALDROP-PERTURBED-COUNT " + PERTURBED_DROPS.size());
        GOLDEN_DROPS.keySet().forEach(key -> System.out.println("REALDROP-GOLDEN " + key));
        PERTURBED_DROPS.keySet().forEach(key -> System.out.println("REALDROP-PERTURBED " + key));
        System.out.println("============== END COMMENT-PRESENCE DIAGNOSTIC ==============\n");
    }

    // ---------------------------------------------------------------------------------------------------------------
    // Comparator core
    // ---------------------------------------------------------------------------------------------------------------

    /** A single dropped comment content together with the input locations it appeared at. */
    record Drop(String content, int inputCount, int outputCount, List<String> inputLocations) {
        @Override
        public String toString() {
            String oneLine = content.replace("\n", "\\n");
            if (oneLine.length() > 140) {
                oneLine = oneLine.substring(0, 137) + "...";
            }
            return "[in=" + inputCount + " out=" + outputCount + " @" + inputLocations + "] \"" + oneLine + "\"";
        }
    }

    /**
     * Returns the comment contents whose multiplicity in the output is strictly lower than in the input — i.e. genuine
     * comment-data-loss. Empty when no content is lost. Normalization (see {@link #normalizeRawComment}) makes
     * re-indentation / trailing-whitespace / block re-shaping invisible, so only genuine absence counts.
     *
     * <p><strong>The lexer token stream is the ground truth for presence.</strong> The drop multiset is computed by
     * counting comment <em>tokens</em> directly from JavaParser's lexer ({@link #lexerCommentCounts}) on the input and
     * on the formatted output. A lexer count cannot phantom-drop or phantom-gain: it counts the actual {@code //} and
     * {@code /* *}{@code /} tokens present in the source bytes. This deliberately does <em>not</em> use
     * {@code getAllContainedComments()} as the primary signal, because that attributed-comment traversal has the same
     * weakness the guardrail does — it can list one {@code Comment} instance twice (manufacturing a phantom drop after
     * reflow) and can omit a comment that survives in the text but attaches where the traversal does not reach (e.g. a
     * leading comment between a {@code package} declaration and the first type, which is present in the output yet absent
     * from {@code getAllContainedComments()}). Both failure modes were observed and would corrupt an AST-primary count.
     *
     * <p>The AST is still parsed, but only to attach best-effort <em>input locations</em> to each dropped content for the
     * report; if the AST cannot locate a dropped content (the omitted-orphan case), the drop is still reported, with an
     * empty location list. A {@code [XCHECK]} line is printed whenever the AST-derived drop magnitude disagrees with the
     * authoritative lexer magnitude, so the divergence between the two witnesses stays visible rather than hidden.
     */
    static List<Drop> realDrops(String source, FormatterOptions options) {
        return realDrops(source, Frmtr.format(source, options), options);
    }

    /**
     * Pure comparator over an arbitrary (input, output) pair, factored out of {@link #realDrops(String,
     * FormatterOptions)} so the comparator itself can be exercised in isolation (feeding a deliberately comment-stripped
     * output) without depending on any particular formatter bug to manufacture a drop.
     */
    static List<Drop> realDrops(String source, String formatted, FormatterOptions options) {
        Map<String, Integer> lexerInput = lexerCommentCounts(source);
        Map<String, Integer> lexerOutput = lexerCommentCounts(formatted);

        // Best-effort AST locations for reporting only; never used to decide whether something dropped.
        Map<String, List<String>> inputLocations = astLocationsByContent(source, options);
        Map<String, Integer> astInput = astCommentCounts(source, options);
        Map<String, Integer> astOutput = astCommentCounts(formatted, options);

        List<Drop> drops = new ArrayList<>();
        for (Map.Entry<String, Integer> entry : lexerInput.entrySet()) {
            String content = entry.getKey();
            int in = entry.getValue();
            int out = lexerOutput.getOrDefault(content, 0);
            int astDrop = astInput.getOrDefault(content, 0) - astOutput.getOrDefault(content, 0);
            if (out < in) {
                drops.add(new Drop(content, in, out, inputLocations.getOrDefault(content, List.of())));
                if (astDrop != in - out) {
                    // AST UNDER-reports a real drop (e.g. an omitted file-leading orphan the traversal never reaches).
                    System.out.println("  [XCHECK] AST under-reports \"" + content.replace("\n", "\\n")
                        + "\": lexer-drop=" + (in - out) + " ast-drop=" + astDrop
                        + " — AST traversal artifact, lexer authoritative (this case IS a real drop)");
                }
            } else if (astDrop > 0) {
                // AST OVER-reports: it counts a drop the lexer (ground truth) refutes — the text is present. This is the
                // guardrail's own failure mode reproduced at the AST level; the case is correctly NOT recorded as a drop.
                System.out.println("  [XCHECK] AST over-reports (NOT a real drop) \"" + content.replace("\n", "\\n")
                    + "\": ast-drop=" + astDrop + " but lexer in=" + in + " out=" + out
                    + " (text present) — accounting gap, excluded from drops");
            }
        }
        return drops;
    }

    private static Map<String, Integer> astCommentCounts(String source, FormatterOptions options) {
        return multiset(commentEntries(parse(source, options)));
    }

    private static Map<String, List<String>> astLocationsByContent(String source, FormatterOptions options) {
        Map<String, List<String>> locations = new LinkedHashMap<>();
        for (CommentEntry entry : commentEntries(parse(source, options))) {
            locations.computeIfAbsent(entry.content(), key -> new ArrayList<>()).add(entry.location());
        }
        return locations;
    }

    /**
     * Counts each comment token's normalized content directly from the lexer stream, ignoring the attributed-comment
     * AST entirely. This is the authoritative presence witness used by {@link #realDrops}: a lexer count cannot
     * phantom-drop or phantom-gain, because it counts the actual comment tokens in the source bytes.
     */
    private static Map<String, Integer> lexerCommentCounts(String source) {
        Map<String, Integer> counts = new LinkedHashMap<>();
        TokenRange tokens = parseResultBleedingEdge(source).getResult()
                .flatMap(CompilationUnit::getTokenRange)
                .orElse(null);
        if (tokens == null) {
            return counts;
        }
        for (JavaToken token : tokens) {
            if (token.getCategory().isComment()) {
                counts.merge(normalizeRawComment(token.getText()), 1, Integer::sum);
            }
        }
        return counts;
    }

    /** Normalizes a raw comment token's text the same way {@link #normalize} normalizes an attributed comment. */
    private static String normalizeRawComment(String raw) {
        String text = raw.strip();
        if (text.startsWith("//")) {
            return text.substring(2).strip();
        }
        String inner = text;
        if (inner.startsWith("/*")) {
            inner = inner.substring(2);
        }
        if (inner.endsWith("*/")) {
            inner = inner.substring(0, inner.length() - 2);
        }
        List<String> lines = new ArrayList<>();
        for (String rawLine : inner.split("\n", -1)) {
            String line = rawLine.strip();
            if (line.startsWith("*")) {
                line = line.substring(1).strip();
            }
            if (!line.isEmpty()) {
                lines.add(line);
            }
        }
        return String.join("\n", lines);
    }

    private static List<Drop> safeRealDrops(String name, String source, FormatterOptions options) {
        try {
            return realDrops(source, options);
        } catch (RuntimeException exception) {
            System.out.println("  [WARN] could not evaluate " + name + ": " + exception.getMessage());
            return List.of();
        }
    }

    private record CommentEntry(String content, String location) {}

    private static List<CommentEntry> commentEntries(CompilationUnit unit) {
        List<CommentEntry> entries = new ArrayList<>();
        // Dedupe by JavaParser object identity. getAllContainedComments() can list the SAME Comment instance twice when
        // it is reachable through more than one traversal path (verified: an enum-constant trailing comment appears twice
        // in the input tree but once in the reflowed output tree). That double-listing is a parser-traversal artifact,
        // not a second copy of the text, so counting it would manufacture phantom drops. Two DISTINCT Comment instances
        // carrying the same text (e.g. two separate `/*dead code*/` comments) are kept separate — only reference-equal
        // duplicates collapse — so genuine multiplicity drops are preserved.
        Set<Comment> seen = Collections.newSetFromMap(new IdentityHashMap<>());
        for (Comment comment : unit.getAllContainedComments()) {
            if (!seen.add(comment)) {
                continue;
            }
            String location = comment.getRange()
                    .map(range -> "L" + range.begin.line + ":C" + range.begin.column)
                    .orElse("L?");
            entries.add(new CommentEntry(normalize(comment), location));
        }
        return entries;
    }

    private static Map<String, Integer> multiset(List<CommentEntry> entries) {
        Map<String, Integer> counts = new LinkedHashMap<>();
        for (CommentEntry entry : entries) {
            counts.merge(entry.content(), 1, Integer::sum);
        }
        return counts;
    }

    /**
     * Normalizes a comment's content so legitimate formatter re-shaping does not read as a difference:
     *
     * <ul>
     *   <li>line comment: text after {@code //}, {@link String#strip stripped};
     *   <li>block / javadoc: inner text split into lines, each line's leading whitespace and a single optional leading
     *       {@code *} removed and trailing whitespace stripped, blank lines dropped, non-blank lines joined with
     *       {@code \n}. Dropping blank interior lines is deliberate — the formatter may add/remove blank lines inside a
     *       block body without losing author text, and we only want to detect genuine absence of words.
     * </ul>
     */
    private static String normalize(Comment comment) {
        String content = comment.getContent();
        if (comment.isLineComment()) {
            return content.strip();
        }
        List<String> lines = new ArrayList<>();
        for (String rawLine : content.split("\n", -1)) {
            String line = rawLine.strip();
            if (line.startsWith("*")) {
                line = line.substring(1).strip();
            }
            if (!line.isEmpty()) {
                lines.add(line);
            }
        }
        return String.join("\n", lines);
    }

    // ---------------------------------------------------------------------------------------------------------------
    // Parsing — match the formatter's configuration (FormatterGuardrails / JavaFormatter).
    // ---------------------------------------------------------------------------------------------------------------

    private static CompilationUnit parse(String source, FormatterOptions options) {
        ParseResult<CompilationUnit> result = newParser(options)
                .parse(ParseStart.COMPILATION_UNIT, Providers.provider(source));
        return result.getResult()
                .orElseThrow(() -> new IllegalStateException("diagnostic parse failed: " + result.getProblems()));
    }

    private static boolean parses(String source, FormatterOptions options) {
        return newParser(options).parse(ParseStart.COMPILATION_UNIT, Providers.provider(source)).isSuccessful();
    }

    private static JavaParser newParser(FormatterOptions options) {
        return new JavaParser(new ParserConfiguration()
                .setLanguageLevel(languageLevel(options))
                .setStoreTokens(true)
                .setAttributeComments(true));
    }

    /** Mirror JavaFormatter.javaParserLanguageLevel so the diagnostic parse matches the formatter's parse exactly. */
    private static ParserConfiguration.LanguageLevel languageLevel(FormatterOptions options) {
        return switch (options.javaLanguageLevel()) {
            case UNSET -> null;
            case LATEST_AVAILABLE -> ParserConfiguration.LanguageLevel.BLEEDING_EDGE;
            case JAVA_8 -> ParserConfiguration.LanguageLevel.JAVA_8;
            case JAVA_9 -> ParserConfiguration.LanguageLevel.JAVA_9;
            case JAVA_10 -> ParserConfiguration.LanguageLevel.JAVA_10;
            case JAVA_11 -> ParserConfiguration.LanguageLevel.JAVA_11;
            case JAVA_12 -> ParserConfiguration.LanguageLevel.JAVA_12;
            case JAVA_13 -> ParserConfiguration.LanguageLevel.JAVA_13;
            case JAVA_14 -> ParserConfiguration.LanguageLevel.JAVA_14;
            case JAVA_15 -> ParserConfiguration.LanguageLevel.JAVA_15;
            case JAVA_16 -> ParserConfiguration.LanguageLevel.JAVA_16;
            case JAVA_17 -> ParserConfiguration.LanguageLevel.JAVA_17;
            case JAVA_18 -> ParserConfiguration.LanguageLevel.JAVA_18;
            case JAVA_19 -> ParserConfiguration.LanguageLevel.JAVA_19;
            case JAVA_20 -> ParserConfiguration.LanguageLevel.JAVA_20;
            case JAVA_21 -> ParserConfiguration.LanguageLevel.JAVA_21;
            case JAVA_22 -> ParserConfiguration.LanguageLevel.JAVA_22;
            case JAVA_23 -> ParserConfiguration.LanguageLevel.JAVA_23;
            case JAVA_24 -> ParserConfiguration.LanguageLevel.JAVA_24;
            case JAVA_25 -> ParserConfiguration.LanguageLevel.JAVA_25;
        };
    }

    // ---------------------------------------------------------------------------------------------------------------
    // Lexer parse for the comment-token ground truth. The corpus perturbation itself lives in SourceShapePerturbation,
    // shared with IdempotencePropertyTest so both tests re-shape the corpus identically.
    // ---------------------------------------------------------------------------------------------------------------

    private static ParseResult<CompilationUnit> parseResultBleedingEdge(String source) {
        return new JavaParser(new ParserConfiguration()
                .setLanguageLevel(ParserConfiguration.LanguageLevel.BLEEDING_EDGE)
                .setStoreTokens(true)
                .setAttributeComments(true))
                .parse(ParseStart.COMPILATION_UNIT, Providers.provider(source));
    }
}
